Pages/Garage1/Bestilling.cshtml.cs
using DriveByBooking.Model.CarFolder;
using DriveByBooking.Model.ProfilFolder;
using DriveByBooking.Model.Booking;
using DriveByBooking.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Globalization;
using System;

namespace DriveByBooking.Pages.Garage1
{
    public class BestillingModel : PageModel
    {
        private loginModel loginModel;
        private ICarRepository _carrepo;
        private ICustomerRepository _customerrepo;
        private IBookingRepository _bookrepo;

        public CarClass Cars { get; private set; }
        public CustomerClass Customer { get; private set; }

        public Booking booking { get; private set; }

        public BestillingModel(ICarRepository carRepository)
        {
            _carrepo = carRepository;
        }
         
        public IActionResult OnGet(string licensplate)
        {
            Cars = _carrepo.GetCar(licensplate); 

            return Page();
        }
        public void OnPost()
        {
            if (!ModelState.IsValid)
            {

            }
            Booking newBooking = new Booking(Cars, Customer, DateTime.Now);

            try
            {
                //KundeRepository repo = new KundeRepository(true);
                _bookrepo.AddBooking(newBooking);
            }
            catch (ArgumentException ae)
            {

            }
        }

        public IActionResult OnPostCancel()
        {
            return RedirectToPage("Index");
        }
    }
}

Pages/Garage1/Confirm.cshtml.cs
using DriveByBooking.Model.Booking;
using DriveByBooking.Model.CarFolder;
using DriveByBooking.Model.ProfilFolder;
using DriveByBooking.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DriveByBooking.Pages.Garage1
{
    public class ConfirmModel : PageModel
    {

        // Repositories for data (dependency injection)
        private ICarRepository _carrepo;
        private ICustomerRepository _customerrepo;
        private IBookingRepository _bookrepo;

        // Properties
        public CustomerClass CustomerClass { get; set; }
        public CarClass Cars { get; set; }
        public loginModel login { get; set; }
        public List<Booking> Books { get; set; }

        // Constructor
        public ConfirmModel(IBookingRepository bookrepo, ICustomerRepository customerRepo, ICarRepository carRepo)
        {
            _bookrepo = bookrepo;
            _customerrepo = customerRepo;
            _carrepo = carRepo;
        }

        // Bindproperty
        [BindProperty]
        public string OrderCustomerUsername { get; set; }

        public string ErrorMessage { get; private set; }

        public IActionResult OnGet(string licensplate, string username)
        {
            Books = _bookrepo.GetAllbookings();
            Cars = _carrepo.GetCar(licensplate); // Adjust this based on your repository method to get a list of cars
            CustomerClass = _customerrepo.CustomerLoggedIn;

            return Page();
        }

        public IActionResult OnPost()
        {

            if (!ModelState.IsValid)
            {
                return Page();
            }

            Booking newBooking = new Booking(Cars, CustomerClass, DateTime.Now);

            try
            {
                //KundeRepository repo = new KundeRepository(true);
                _bookrepo.AddBooking(newBooking);
                TempData["SuccessMessage"] = $"Booking {newBooking} added successfully";
            }
            catch (ArgumentException ae)
            {
                ErrorMessage = ae.Message;
                return Page();
            }

            return RedirectToPage("Index");

        }
    }
}

Pages/Garage1/Index.cshtml.cs
using DriveByBooking.Model.CarFolder;
using DriveByBooking.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DriveByBooking.Pages.Garage1
{
    public class IndexModel : PageModel
    {
        // Repository for data (dependency injection)
        private ICarRepository _list;


        // Contructor
        public IndexModel(ICarRepository list)
        {
            _list = list;
        }

        // List property
        public List<CarClass> Cars { get; set; }

        // BindProperties
        [BindProperty]
        public string? SearchLicensePlate { get; set; }
        [BindProperty]
        public string? SearchCarName { get; set; }
        [BindProperty]
        public string? SearchBrand { get; set; }
        [BindProperty]
        public double? SearchPrice { get; set; }
        [BindProperty]
        public double? FindPrice { get; set; }
        [BindProperty]
        public string? SearchType { get; set; }
        [BindProperty]
        public string? SearchCarType { get; set; }
        [BindProperty]
        public string? SearchShiftType { get; set; }
        [BindProperty]
        public string? SearchEngineType { get; set; }
        [BindProperty]
        public string? SearchLocation { get; set; }
        [BindProperty]
        public string? CollectLocation { get; set; }


        // HTTP GET method to handle intial page loading:
        public void OnGet()
        {
            Cars = _list.GetAllCars();
        }


        // HTTP POST method to handle form submissions:
        public RedirectToPageResult OnPost()
        {
            return RedirectToPage("Index");
        }

        public IActionResult OnGetsearch()
        {
            Cars = _list.SearchPrice(FindPrice);
            return Page();
        }

        public IActionResult OnPostSearch()
        {
            Cars = _list.Search(SearchLicensePlate, SearchCarName, SearchBrand, SearchPrice, SearchType, SearchCarType, SearchShiftType, SearchEngineType, SearchLocation);
            return Page();
        }

        public RedirectToPageResult OnPostOrder()
        {
            return RedirectToPage("Index");
        }
    }
}

Pages/Garage1/Bestilling.cshtml
@page
@model DriveByBooking.Pages.Garage1.BestillingModel
@{
}
<h1>Booking side</h1>
<div class="form-selectt">
    <form method="post">
        <div class="form-group">

            <label>Bilens Nummerplade</label> : @Model.Cars.LicensePlate<br />
            <br />
            <label>Bilens Navn</label> : @Model.Cars.Name<br />
            <br />
            <label>Brand</label>  : @Model.Cars.Brand<br />
            <br />
            <label>Pris</label>  : @Model.Cars.Price<br />
            <br />
            <label>Type</label>  : @Model.Cars.Type<br />
            <br />
            <label>EngineType</label>  : @Model.Cars.EngineType<br />
            <br />

            <input type="submit" value="Order" class="btn btn-danger" asp-page="Confirm" />
            <input type="submit" value="Cancel" class="btn btn-warning" asp-page-handler="Cancel" />
        </div>
    </form>
</div>

Pages/Garage1/Confirm.cshtml
@page
@model DriveByBooking.Pages.Garage1.ConfirmModel
@{
}
<h1>TAK FOR DIN BESTILLING!!!</h1>

<form method="post">
    <div class="form-group>">
        <h3>For at booke den valgte bil skal du indtaste dine oplysninger</h3>
        <label>Kunde Username</label><br />
        <input class="form-control" asp-for="@Model.OrderCustomerUsername" /><br />
        <br />

        <input type="submit" value="BOOK" class="btn btn-success" asp-route-username="@Model.OrderCustomerUsername" />
        <input type="submit" value="Fortryd" class="btn btn-danger" asp-page-handler="Cancel" />
    </div>
</form>

Pages/Garage1/Index.cshtml
@page
@using DriveByBooking.Model.CarFolder;
@model DriveByBooking.Pages.Garage1.IndexModel
@{
    ViewData["PriceRange"] = "range auto update";
}

<div class="text-white p-5 my-7 gap-5" >
    <div class="bg-dark rounded-2">
    <form method="post" class="border border-success rounded p-1">
        <input type="submit" asp-page-handler="Search" value="Søg" class="btn btn-outline-success" />
            <div class="row-cols-1 form-outline mb-4">
                <label class="form-label">Navn </label>
                <input type="text" asp-for="@Model.SearchCarName" />
                <label class="form-label">Brand </label>
                <input type="text" asp-for="@Model.SearchBrand" />
            </div>
        <input type="range" asp-for="@Model.SearchPrice" id="priceRange" class="form-range" name="priceRange" min="0" max="20000" step="500" value="@Model.SearchPrice" />
    <div class="container">
        <ul class="list-unstyled d-flex justify-content-between">
            <li>Min  : 0 kr.</li>
            <li><input asp-for="@Model.SearchPrice" hidden/><output form="get" id="priceOutput">@Model.SearchPrice.GetValueOrDefault()</output></li>
            <li>Maks : 20.000 kr.</li>
        </ul>
    </div>

        <select asp-for="@Model.SearchCarType" class="form-select">
            <option value="" asp-for="@Model.SearchCarType"> Bil Typer</option>
            <option value="" asp-for="@Model.SearchCarType"> Alle Bil Typer</option>
            <option value="SUV" asp-for="@Model.SearchCarType"> SUV</option>
            <option value="Hatchback" asp-for="@Model.SearchCarType"> Hatchback</option>
            <option value="Staioncar" asp-for="@Model.SearchCarType"> Staioncar</option>
            <option value="MPV" asp-for="@Model.SearchCarType"> MPV</option>
            <option value="Cabriolet" asp-for="@Model.SearchCarType"> Cabriolet</option>
        </select>

        <select asp-for="@Model.SearchShiftType" class="form-select">
            <option value="" asp-for="@Model.SearchShiftType"> Gear kasse Typer</option>
            <option value="" asp-for="@Model.SearchShiftType"> Alle Gear kasser</option>
            <option value="Automat" asp-for="@Model.SearchShiftType"> Automat Gear</option>
            <option value="Manuel" asp-for="@Model.SearchShiftType"> Manuelle Gear</option>
        </select>

        <select asp-for="@Model.SearchEngineType"class="form-select">
            <option value="" asp-for="@Model.SearchEngineType"> Motor Typer</option>
            <option value="" asp-for="@Model.SearchEngineType"> Alle Motorer</option>
            <option value="Benzin" asp-for="@Model.SearchEngineType"> Benzin</option>
            <option value="Diesel" asp-for="@Model.SearchEngineType"> Diesel</option>
            <option value="Hybrid" asp-for="@Model.SearchEngineType"> Hybrid</option>
            <option value="Elektrisk" asp-for="@Model.SearchEngineType"> Elektrisk</option>
        </select>

        <select asp-for="@Model.SearchLocation" class="form-select">
            <option value="" asp-for="@Model.SearchLocation"> Lokationer</option>
            <option value="" asp-for="@Model.SearchLocation"> Alle Lokationer</option>
            <option value="Aarhus" asp-for="@Model.SearchLocation"> Aarhus</option>
            <option value="Aalborg" asp-for="@Model.SearchLocation"> Aalborg</option>
            <option value="Fredericia" asp-for="@Model.SearchLocation"> Fredericia</option>
            <option value="Søborg" asp-for="@Model.SearchLocation"> Søborg</option>
        </select>
    </form>
    </div>
</div>

 <div class="row justify-content-evenly gap-5">
  
    @foreach (var cars in Model.Cars)
    {
        if (!cars.IsBooked)
        {
            <div class="card bg-dark" style="width: 20em">
                <div>
                    <div class="container p-5 my-5">
                        <div class="card-subtitle ">
                            <h2 class="gradient-text">@cars.Brand</h2>
                            <h3 class="gradient-text">@cars.Name</h3>
                        </div>
                        <div class="card-body text-white">
                            <ul>
                                <li><p>Motor type: @cars.EngineType </p></li>
                                <li><p>Gear Kasse: @cars.ShiftType</p></li>
                                <li><p>Lokation: @cars.Location</p></li>
                                <li><p>Pris: @cars.Price Kr.</p></li>
                            </ul>
                            <div class="d-grid">
                                <a class="btn btn-block bestil" asp-page="Bestilling" asp-route-licensplate="@cars.LicensePlate">BESTIL</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
        else
        {
            <p>ingen resultater</p>
        }
    }

</div>

@section Scripts {
    <script>
        const priceRange = document.getElementById('priceRange');
        const priceOutput = document.getElementById('priceOutput');

        function updatePrice() {
            const selectedPrice = parseFloat(priceRange.value);
            priceOutput.textContent = "Maks Pris: " + selectedPrice.toLocaleString() + " Kr.";
            localStorage.setItem('selectedPrice', selectedPrice);
        }

        priceRange.addEventListener('input', updatePrice);

        const savedPrice = localStorage.getItem('selectedPrice');
        if (savedPrice !== null) {
            priceRange.value = savedPrice;
            updatePrice();
        }
    </script>
}